/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/allographs': RouteRecordInfo<'/allographs', '/allographs', Record<never, never>, Record<never, never>>,
    '/inscriptions': RouteRecordInfo<'/inscriptions', '/inscriptions', Record<never, never>, Record<never, never>>,
    '/keyboard': RouteRecordInfo<'/keyboard', '/keyboard', Record<never, never>, Record<never, never>>,
    '/signGraph': RouteRecordInfo<'/signGraph', '/signGraph', Record<never, never>, Record<never, never>>,
    '/signs': RouteRecordInfo<'/signs', '/signs', Record<never, never>, Record<never, never>>,
  }
}
